### ISSUE TITLE
5.4.51-v7+ USBridge Sig driver broken (?)

### ISSUE THREAD

**Issue by MichaIng** [allocom/USBridgeSig#1]
Hey @sudeepkumar, we got the following bug report: https://github.com/MichaIng/DietPi/issues/3725
It seems that [this](http://3.230.113.73:9011/Allocom/USBridgeSig/rpi-usbs-5.4.51-v7+/ax88179_178a.ko) driver does not work with the current official RPi kernel on ARMv7. Could you have a look?

**Comment by MichaIng** [comment]
While trying to compile the module myself, I ran into an error due to this: https://github.com/allocom/USBridgeSig/blob/master/ethernet/ax88179_178a.c#L1948-L1949
Those two options have been removed: https://patchwork.kernel.org/patch/10578933/
Commenting the two lines solves to compiling issue, but not sure about side effects when this is missing. There are new options replacing those but I have no idea how to use them correctly, simply replacing `[gs]et_settings` with `[gs]et_link_ksettings` does not work. Testing by user in process.

What did you about this to be able to compile the module for the latest kernel versions?
If not yet done, makes sense to report this to ASIX, if there is any plan to merge this into Linux upstream.

**Comment by antonellocaroli** [comment]
why are you trying to compile this and not this?

https://github.com/allocom/USBridgeSig-AX2v0

**Comment by MichaIng** [comment]
I didn't know about the update, thanks for the information, will try it out. [This](http://3.230.113.73:9011/Allocom/USBridgeSig/rpi-usbs-5.4.51-v7+/ax88179_178a.ko) is based on the new version then as well? The issue remains that it fails to load on current official RPi Linux `5.4.51-v7+`.
__________
Just done, yes the new version compiles fine, aside or one warning:
```
/tmp/ax88179_178a.c: In function ‘ax_intr_callback’:
/tmp/ax88179_178a.c:529:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
   netif_device_detach(axdev->netdev);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/ax88179_178a.c:530:2: note: here
  case -ENOENT:
  ^~~~
```

**Comment by antonellocaroli** [comment]
> [This](http://3.230.113.73:9011/Allocom/USBridgeSig/rpi-usbs-5.4.51-v7+/ax88179_178a.ko) is based on the new version then as well?
>
I think so

**Comment by MichaIng** [comment]
Okay initial issue solved by the new driver version, I mark this hence as closed 👍.
